theme: jekyll-theme-architect

title: [codemodel]
description: [A Java library for code generators]

# sidebar links url
links:
  source: https://github.com/javaee/codemodel
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

